version: "3.1"
services:
    www:
        build: .
        ports:
            - "8000:80"
        volumes:
            - ./www:/var/www/html/public/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password

        environment:
            MYSQL_DATABASE: pastel
            MYSQL_USER: pastel
            MYSQL_PASSWORD: r00T
            MYSQL_ROOT_PASSWORD: r00T
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
